name: Latest
on:
  push:
    branches:
    - master
permissions:
  id-token: write
  contents: read
concurrency: latest
defaults:
  run:
    shell: bash
jobs:
  latest:
    runs-on: ['hyperenv', 'medium-eu-west-1']
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::820394158530:role/github-openid-connect
        role-session-name: github-actions-aws-cf-templates
        aws-region: eu-west-1
    - name: latest
      run: |
        sed -i "s/__VERSION__/latest/g" ./*/*.yaml
        aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*" --exclude "test/*" --exclude "docs/*" ./ s3://widdix-aws-cf-templates/
        aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*" --exclude "test/*" --exclude "docs/*" ./ s3://widdix-aws-cf-templates-releases-eu-west-1/latest/
