name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        default: '1.0.0'
      company:
        description: 'Company Name'
        required: true
        default: 'adappt.ai'
      environment:
        description: 'Environment'
        required: true
        default: 'local'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: rabbitmq
        run: |
          cp fargate/service-cloudmap-cluster-alb-secrets.yaml fargate/service-rabbitmq-cloudmap-cluster-alb-secrets.yaml
          sed -i 's|fargate/service-cloudmap-cluster-alb-secrets|fargate/service-rabbitmq-cloudmap-cluster-alb-secrets|g' fargate/service-rabbitmq-cloudmap-cluster-alb-secrets.yaml
          sed -i 's|- ContainerPort: !Ref AppPort|- ContainerPort: !Ref AppPort\n        - ContainerPort: 5672\n        - ContainerPort: 4369\n        - ContainerPort: 25672|' fargate/service-rabbitmq-cloudmap-cluster-alb-secrets.yaml

      - name: locust-master
        run: |
          cp fargate/service-cloudmap-cluster-alb-secrets.yaml fargate/service-locust-master-cloudmap-cluster-alb-secrets.yaml
          sed -i 's|fargate/service-cloudmap-cluster-alb-secrets|fargate/service-locust-master-cloudmap-cluster-alb-secrets|g' fargate/service-locust-master-cloudmap-cluster-alb-secrets.yaml
          sed -i 's|- ContainerPort: !Ref AppPort|- ContainerPort: !Ref AppPort\n        - ContainerPort: 5557|' fargate/service-locust-master-cloudmap-cluster-alb-secrets.yaml
  
      - name: Replace IPv6 settings and create copies
        run: |
          find . -type f -name '*.yaml' | while read file; do
            if grep -q '#AssignIpv6AddressOnCreation: true' "$file" && grep -q 'MapPublicIpOnLaunch: true' "$file"; then
              new_file="${file%.yaml}-ipv6.yaml"
              cp "$file" "$new_file"
              sed -i 's|#AssignIpv6AddressOnCreation: true|AssignIpv6AddressOnCreation: true|g' "$new_file"
              sed -i 's|MapPublicIpOnLaunch: true|#MapPublicIpOnLaunch: true|g' "$new_file"
            fi
          done

      - name: company
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "cloudonaut.io"
          replace: "${{ github.event.inputs.company }}"

      - name: version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__VERSION__"
          replace: "${{ github.event.inputs.version }}"

      - name: content-1
        run: |
          find . -type f -name '*.yaml' | while read file; do set -ex && sed -i "/# Copyright 2018 widdix GmbH/,+12 d" "$file"; done;

      - name: content-2
        run: |
          find . -type f -name '*.yaml' | while read file; do set -ex && sed -i "/# Copyright 2019 widdix GmbH/,+12 d" "$file"; done;

      - name: wait
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "waits for https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/655"
          replace: "still work in progress"

      - name: sponsored
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", sponsored by https://github.com/ngault"
          replace: "."

      - name: contributed-1
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/btsuhako"
          replace: "."

      - name: contributed-2
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/statik"
          replace: "."

      - name: contributed-3
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/shotty1"
          replace: "."

      - name: appimage
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "widdix/hello:v1"
          replace: "nginx:latest"

      - name: httpcode
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "200-299"
          replace: "200-499"

      - name: domain
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "widdix.de"
          replace: "adappt.ai"

      - name: Configure AWS Credentials
        if: ${{ github.event.inputs.environment != 'local' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy the files to S3 bucket
        if: ${{ github.event.inputs.environment != 'local' }}
        run: aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude '.yamllint' --exclude 'LICENSE' --exclude 'mkdocs.yml' --exclude 'README.md' --exclude '.readthedocs.yaml' --exclude 'setup.py' --exclude 'docs/*' --exclude 'test/*' --exclude '*.js' --exclude '*.md' --delete

      - name: Save files as artifact
        if: ${{ github.event.inputs.environment == 'local' }}
        uses: actions/upload-artifact@v3
        with:
          name: deployment-files
          path: |
            **
            !.git/**
            !.github/**
            !.gitignore
            !.yamllint
            !LICENSE
            !mkdocs.yml
            !README.md
            !.readthedocs.yaml
            !setup.py
            !docs/**
            !test/**
            !**/*.js
            !**/*.md
