name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        default: '1.0.0'
      company:
        description: 'Company Name'
        required: true
        default: 'adappt.ai'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: company
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "cloudonaut.io"
          replace: "${{ github.event.inputs.company }}"

      - name: version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__VERSION__"
          replace: "${{ github.event.inputs.version }}"

      - name: content-1
        run: |
          find . -type f -name '*.yaml' | while read file; do set -ex && sed -i "/# Copyright 2018 widdix GmbH/,+12 d" "$file"; done;

      - name: content-2
        run: |
          find . -type f -name '*.yaml' | while read file; do set -ex && sed -i "/# Copyright 2019 widdix GmbH/,+12 d" "$file"; done;

      - name: wait
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "waits for https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/655"
          replace: "still work in progress"

      - name: sponsored
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", sponsored by https://github.com/ngault"
          replace: "."

      - name: contributed-1
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/btsuhako"
          replace: "."

      - name: contributed-2
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/statik"
          replace: "."

      - name: contributed-3
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: ", contributed by https://github.com/shotty1"
          replace: "."

      - name: domain
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "widdix.de"
          replace: "adappt.co.uk"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy the files to S3 bucket
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude '.yamllint' --exclude 'LICENSE' --exclude 'mkdocs.yml' --exclude 'README.md' --exclude 'setup.py' --exclude 'docs/*' --exclude 'test/*' --exclude '*.md' --delete
