name: Release
on:
  push:
    tags:
    - v*
permissions:
  id-token: write
  contents: read
defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ['hyperenv', 'medium-eu-west-1']
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::820394158530:role/github-openid-connect
        role-session-name: github-actions-aws-cf-templates
        aws-region: eu-west-1
    - name: release
      run: |
        VERSION=${GITHUB_REF_NAME:1}
        sed -i "s/__VERSION__/${VERSION}/g" ./*/*.yaml
        aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*" --exclude "test/*" --exclude "docs/*" ./ "s3://widdix-aws-cf-templates-releases-eu-west-1/v${VERSION}/"
        if [[ $VERSION =~ ^[0-9.]*$ ]]; then
          aws s3 sync --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*" --exclude "test/*" --exclude "docs/*" ./ s3://widdix-aws-cf-templates-releases-eu-west-1/stable/
        fi
